--CREATE DATABASE [123mua.vn];
--GO

USE [123mua.vn];
GO

CREATE TABLE dbo.[EMPLOYEE](
  ID CHAR(30) NOT NULL PRIMARY KEY,
  Name NVARCHAR(30) NOT NULL,
  Email CHAR(30) NOT NULL,
  Address NVARCHAR(MAX) NOT NULL,
  [Phone#] VARCHAR(11) NOT NULL,
);

CREATE TABLE dbo.[STORE](
  ID CHAR(30) NOT NULL PRIMARY KEY,
  Name NVARCHAR(30) NOT NULL,
  Email CHAR(30) NOT NULL,
  SignUpDate DATE NOT NULL,
  Address NVARCHAR(MAX) NOT NULL,
  [Phone#] VARCHAR(11) NOT NULL
);

CREATE TABLE dbo.[MEMBER](
  ID CHAR(30) NOT NULL PRIMARY KEY,
  Name NVARCHAR(30) NOT NULL,
  Email CHAR(30) NOT NULL,
  Gender NVARCHAR(30) DEFAULT N'Chưa biết' NOT NULL,
  DayOfBirth DATE NOT NULL,
  Address NVARCHAR(MAX) NOT NULL,
  [Phone#] VARCHAR(11) NOT NULL,
  Hobby NVARCHAR(MAX)
);

CREATE TABLE dbo.[PRODUCT](
  Code CHAR(30) NOT NULL PRIMARY KEY,
  StoreID CHAR(30) NOT NULL FOREIGN KEY REFERENCES STORE(ID),
  Name NVARCHAR(30) NOT NULL,
  Detail NVARCHAR(MAX),
  Price INT NOT NULL,
  PriceDiscount INT,
  UploadDate DATE NOT NULL,
  Location NVARCHAR(30) NOT NULL
);

CREATE TABLE dbo.[Like](
  MemberID CHAR(30) NOT NULL,
  ProductCode CHAR(30) NOT NULL,
  PRIMARY KEY (MemberID, ProductCode),
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (ProductCode) REFERENCES PRODUCT(Code)
);

CREATE TABLE dbo.[Vote](
  MemberID CHAR(30) NOT NULL,
  ProductCode CHAR(30) NOT NULL,
  Rate INT NOT NULL,
  Content NVARCHAR(MAX),
  PRIMARY KEY (MemberID, ProductCode),
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (ProductCode) REFERENCES PRODUCT(Code)
);

CREATE TABLE dbo.[Message](
  SentTime DATETIME NOT NULL PRIMARY KEY,
  MemberID CHAR(30) NOT NULL,
  StoreID CHAR(30) NOT NULL,
  Title NVARCHAR(30) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  Sender NVARCHAR(30) DEFAULT N'Thành viên' NOT NULL, --________________ TRIGGER
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (StoreID) REFERENCES STORE(ID)
);

CREATE TABLE dbo.[Report](
  MemberID CHAR(30) NOT NULL,
  ProductCode CHAR(30) NOT NULL,
  EmployeeID CHAR(30) NOT NULL,
  CheckStatus NVARCHAR(30) DEFAULT N'Chưa duyệt' NOT NULL,
  PRIMARY KEY (MemberID, ProductCode, EmployeeID),
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (ProductCode) REFERENCES PRODUCT(Code),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE dbo.[Comment](
  SentTime DATETIME NOT NULL PRIMARY KEY,
  MemberID CHAR(30) NOT NULL,
  ProductCode CHAR(30) NOT NULL,
  EmployeeID CHAR(30) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  CheckStatus NVARCHAR(30) DEFAULT N'Chưa duyệt' NOT NULL,
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(ID),
  FOREIGN KEY (ProductCode) REFERENCES PRODUCT(Code)
);

CREATE TABLE dbo.[Order](
  Code CHAR(30) NOT NULL,
  StoreID CHAR(30) NOT NULL,
  MemberID CHAR(30) NOT NULL,
  ProductCode CHAR(30) NOT NULL,
  Amount INT CHECK (Amount > 0),
  Cost INT NOT NULL,
  Requires NVARCHAR(MAX),
  OrderDate DATE NOT NULL,
  OrderStatus NVARCHAR(30) NOT NULL,
  PRIMARY KEY (Code, MemberID, ProductCode, StoreID),
  FOREIGN KEY (MemberID) REFERENCES MEMBER(ID),
  FOREIGN KEY (ProductCode) REFERENCES PRODUCT(Code),
  FOREIGN KEY (StoreID) REFERENCES STORE(ID)
);

-- DROP TABLE dbo.toOrder;
-- DROP TABLE dbo.toComment;
-- DROP TABLE dbo.toLike;
-- DROP TABLE dbo.toVote;
-- DROP TABLE dbo.PRODUCT;
-- DROP TABLE dbo.MEMBER;
-- DROP TABLE dbo.STORE;
-- DROP TABLE dbo.EMPLOYEE;
--
--DROP DATABASE [123mua.vn];
